### ISSUE TITLE
Rails 3 support

### ISSUE THREAD

**Issue by dmathieu** [jamesgolick/timeline_fu#2]
Hey,

Have you planned to add rails3 compatibility?

**Comment by jamesgolick** [comment]
I haven't thought about it. Is there really much to change?

**Comment by aaronchi** [comment]
Would be nice to have a new generator and a gem on rubygems

**Comment by DavertMik** [comment]
Seems like plugin works fine with rails 3

**Comment by alec-c4** [comment]
hi,
do you planning to release this plugin as gem?

**Comment by jamesgolick** [comment]
Added the rails3 generator. It's in master, but yet unreleased.
